spring:
  jpa:        database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: GESTIONSALUD
    password: GESTIONSALUD
    